version: '3'

services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    logging:
      driver: none

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: anima
      DB_USER: postgres
      DB_PASSWORD: qwerty123
      KEYCLOAK_LOGLEVEL: DEBUG
    image: jboss/keycloak:latest
    ports:
      - "8787:8080"
    restart: unless-stopped
#    logging:
#      driver: none

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
      - "${MINIO_SERVER_PORT}:${MINIO_SERVER_PORT}"
    env_file:
      - .env
    command: server --address 0.0.0.0:${MINIO_SERVER_PORT} --console-address 0.0.0.0:${MINIO_CONSOLE_PORT} /data
    volumes:
      - minio-data:/data
    logging:
      driver: none

  minio-proxy:
    image: nginx:latest
    volumes:
      - ./minio-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "443:443"

  api-gateway:
    build:
      context: api_gateway
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0"
    ports:
      - "${API_GATEWAY_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./api_gateway:/app

  file-service:
    build:
      context: file_service
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0"
    ports:
      - "${FILE_SERVICE_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./file_service:/app

volumes:
  pg-data:
  minio-data: