version: '3'

services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    logging:
      driver: none

  project-service-db:
    image: postgres:14.2
    ports:
      - "30432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-project-service-data:/var/lib/postgresql/data

    logging:
      driver: none

  animation-service-db:
    image: postgres:14.2
    ports:
      - "31432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-animation-service-data:/var/lib/postgresql/data

    logging:
      driver: none

  project-service:
    build:
      context: project_service
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: project-service-db
    volumes:
      - ./project_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - project-service-db
      - keycloak

  animation-service:
    build:
      context: animation_service
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: animation-service-db
    volumes:
      - ./animation_service:/app
    ports:
      - "8001:8000"
    depends_on:
      - animation-service-db
      - keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    logging:
      driver: none
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: anima
      DB_USER: postgres
      DB_PASSWORD: qwerty123
    image: jboss/keycloak:latest
    ports:
      - "8787:8080"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    env_file:
      - .env
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    volumes:
      - minio-data:/data

volumes:
  pg-data:
  pg-project-service-data:
  pg-animation-service-data:
  minio-data: