"""change File.size type

Revision ID: 168ad8b2e4a4
Revises: a520feb3a599
Create Date: 2022-12-07 19:41:47.050954

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '168ad8b2e4a4'
down_revision = 'a520feb3a599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'size',
                    existing_type=sa.VARCHAR(),
                    type_=sa.BigInteger(),
                    existing_nullable=True,
                    postgresql_using='size::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'size',
                    existing_type=sa.BigInteger(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
