"""add UniqueConstraint to File

Revision ID: 20b44a9d01a2
Revises: 168ad8b2e4a4
Create Date: 2022-12-07 19:54:42.908300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b44a9d01a2'
down_revision = '168ad8b2e4a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('file_author_filename_uc', 'file', ['author_id', 'initial_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_author_filename_uc', 'file', type_='unique')
    # ### end Alembic commands ###
