"""add file

Revision ID: a520feb3a599
Revises: 
Create Date: 2022-12-07 17:15:30.021460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a520feb3a599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('bucket_name', sa.String(), nullable=True),
    sa.Column('minio_path', sa.String(), nullable=True),
    sa.Column('initial_filename', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_author_id'), 'file', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_author_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
