"""compiled_animation

Revision ID: c9f7132cc0c1
Revises: eefa059548b9
Create Date: 2023-03-13 20:54:12.604042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9f7132cc0c1'
down_revision = 'eefa059548b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compiled_animation',
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('animation_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['animation_id'], ['file_service.file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file_service.file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['file_service.file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('model_id', 'animation_id', name='_model_id_animation_id_uc'),
    schema='file_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compiled_animation', schema='file_service')
    # ### end Alembic commands ###
