"""file table

Revision ID: eefa059548b9
Revises: 
Create Date: 2023-02-15 19:19:23.954696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eefa059548b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('bucket_name', sa.String(), nullable=True),
    sa.Column('minio_path', sa.String(), nullable=True),
    sa.Column('initial_filename', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'initial_filename', name='file_author_filename_uc'),
    schema='file_service'
    )
    op.create_index(op.f('ix_file_service_file_author_id'), 'file', ['author_id'], unique=False, schema='file_service')
    op.create_table('file_meta',
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_service.file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id'),
    schema='file_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_meta', schema='file_service')
    op.drop_index(op.f('ix_file_service_file_author_id'), table_name='file', schema='file_service')
    op.drop_table('file', schema='file_service')
    # ### end Alembic commands ###
