"""change fields of Animation

Revision ID: 606341b71d6b
Revises: b81c709b53f3
Create Date: 2022-12-07 21:10:04.409042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606341b71d6b'
down_revision = 'b81c709b53f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animation', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('animation', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animation', 'updated_at')
    op.drop_column('animation', 'created_at')
    # ### end Alembic commands ###
