"""change fields of Animation

Revision ID: b81c709b53f3
Revises: 082b6a2828e4
Create Date: 2022-12-07 21:09:48.225116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b81c709b53f3'
down_revision = '082b6a2828e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animation', 'updated_at')
    op.drop_column('animation', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animation', sa.Column('created_at', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('animation', sa.Column('updated_at', postgresql.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
