"""animation

Revision ID: f5e8656f50e9
Revises: 
Create Date: 2022-12-05 19:16:22.675898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5e8656f50e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=55), nullable=True),
    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('minio_file_url', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.UUID(), nullable=True),
    sa.Column('updated_at', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animation_project_id'), 'animation', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animation_project_id'), table_name='animation')
    op.drop_table('animation')
    # ### end Alembic commands ###
